import { Poppins } from "next/font/google";
import "./globals.css";
import dns from "node:dns/promises";
dns.setServers(["1.1.1.1", "8.8.8.8"]);



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
